development:
  adapter: postgresql
  encoding: unicode
  database: nifty_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nifty_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: nifty_production
  pool: 5
  username:
  password:
